#!/usr/bin/env node
/**
 * Installs (or removes) the Ensemble behavior runtime as an OMP/Pi extension.
 *
 *   node scripts/install.mjs            build + install
 *   node scripts/install.mjs --uninstall remove the shim
 *   node scripts/install.mjs --status    report what is installed
 *
 * The installed file is a SHIM, not the extension itself. It loads a fully
 * bundled build via createRequire.
 *
 * Why a bundle: two simpler approaches both failed inside the host with
 * "Cannot find module '@sinclair/typebox'" -- a bare ESM import of the TS
 * source, and createRequire against the plain tsc build. The host resolves
 * the extension file but not its node_modules lookups, so any bare specifier
 * fails regardless of module system. Bundling leaves nothing to resolve
 * except node: builtins.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const EXT_DIR = join(homedir(), ".omp", "agent", "extensions");
const SHIM = join(EXT_DIR, "ensemble-behavior-runtime.ts");
const BUNDLE = join(PKG, "dist", "extension.bundle.cjs");

const arg = process.argv[2];

if (arg === "--status") {
  const installed = existsSync(SHIM);
  console.log(`shim:   ${installed ? SHIM : "not installed"}`);
  if (installed) {
    console.log(`bundle: ${existsSync(BUNDLE) ? BUNDLE : "MISSING -- run without --status to rebuild"}`);
    if (existsSync(BUNDLE)) console.log(`built:  ${statSync(BUNDLE).mtime.toISOString()}`);
  }
  process.exit(0);
}

if (arg === "--uninstall") {
  if (existsSync(SHIM)) {
    rmSync(SHIM);
    console.log(`removed ${SHIM}`);
  } else {
    console.log("nothing to remove");
  }
  process.exit(0);
}

console.log("building bundle...");
execFileSync(
  "bun",
  ["build", "src/extension.ts", "--target=node", `--outfile=${BUNDLE}`, "--format=cjs"],
  { cwd: PKG, stdio: "inherit" },
);
if (!existsSync(BUNDLE)) {
  console.error("build produced no bundle; refusing to install a shim that cannot load");
  process.exit(1);
}

mkdirSync(EXT_DIR, { recursive: true });
writeFileSync(
  SHIM,
  `/**
 * Ensemble behavior runtime -- generated by packages/pi-extension/scripts/install.mjs.
 * Edit the source package, then re-run that script. Changes here are lost.
 *
 * This extension loads in EVERY session but arms only in repositories that
 * contain .ensemble/behaviors/ (or a package that ships behaviours). Elsewhere
 * it discovers nothing, does nothing, and writes nothing.
 */
import { createRequire } from "node:module";

let inner;
try {
  inner = createRequire(${JSON.stringify(BUNDLE)})(${JSON.stringify(BUNDLE)});
  inner = inner?.default ?? inner;
} catch (e) {
  console.error("[ensemble] extension failed to load:", e?.message ?? e);
}

export default function (pi) {
  if (typeof inner !== "function") return;
  try {
    inner(pi);
  } catch (e) {
    console.error("[ensemble] extension failed to activate:", e?.message ?? e);
  }
}
`,
);

console.log(`installed ${SHIM}`);
console.log(`  -> ${BUNDLE}`);
console.log("");
console.log("Active only in repositories containing .ensemble/behaviors/.");
console.log("Verify with:  omp -p --no-session 'hi'  then check .ensemble/runtime-log.jsonl");
console.log("Remove with:  node scripts/install.mjs --uninstall");
